# Generated by Django 4.2.8 on 2026-02-05 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('specialty_strength', models.BooleanField(default=False)),
                ('specialty_cardio', models.BooleanField(default=False)),
                ('specialty_flexibility', models.BooleanField(default=False)),
                ('specialty_sports', models.BooleanField(default=False)),
                ('specialty_rehabilitation', models.BooleanField(default=False)),
                ('certifications', models.TextField(blank=True, help_text='Comma-separated certifications', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainer_profiles',
            },
        ),
    ]
