# Generated by Django 4.2.8 on 2026-03-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When True, AI-suggested schedule adjustments are paused. The user has explicitly locked this schedule for the current cycle.'),
        ),
    ]
