# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trainerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Only published programs appear in browsing.'),
        ),
    ]
