# Generated by Django 4.2.8 on 2026-03-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userschedule_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedule',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='userschedule',
            name='adjustment_log',
            field=models.JSONField(blank=True, default=list, help_text='Log of AI adjustments applied to this schedule.', null=True),
        ),
    ]
