# Generated by Django 4.2.8 on 2026-02-10 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_exerciseset_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='session_length',
            field=models.IntegerField(help_text='Minutes per session'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='weekly_frequency',
            field=models.IntegerField(help_text='Number of workouts per week'),
        ),
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.workoutplan')),
            ],
            options={
                'db_table': 'program_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, help_text='Time in seconds', null=True)),
                ('rest', models.IntegerField(default=0, help_text='Rest time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.exercise')),
            ],
            options={
                'db_table': 'exercise_sets',
                'ordering': ['set_number'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.programsection'),
        ),
    ]
