# Generated by Django 4.2.8 on 2026-02-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exercise_alter_workoutplan_session_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='is_subscription',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
