# Generated by Django 4.2.8 on 2026-02-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_exercisetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programsection',
            name='created_at',
        ),
        migrations.AddField(
            model_name='programsection',
            name='is_rest_day',
            field=models.BooleanField(default=False, help_text='Whether this day is a rest day'),
        ),
        migrations.AlterField(
            model_name='programsection',
            name='format',
            field=models.CharField(help_text="Day name (e.g., 'Monday', 'Tuesday')", max_length=50),
        ),
        migrations.AlterField(
            model_name='programsection',
            name='type',
            field=models.CharField(blank=True, help_text="Optional day description (e.g., 'Upper Body', 'Chest Day')", max_length=100),
        ),
        migrations.AddIndex(
            model_name='programsection',
            index=models.Index(fields=['program', 'order'], name='program_sec_program_434b02_idx'),
        ),
    ]
