# Generated by Django 4.2.8 on 2026-02-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedule',
            name='program',
        ),
        migrations.AddField(
            model_name='userschedule',
            name='programs',
            field=models.ManyToManyField(related_name='user_schedules', to='api.workoutplan'),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='weekly_schedule',
            field=models.JSONField(default=dict, help_text="Maps days of week to lists of program section IDs or 'rest'"),
        ),
    ]
