# Generated by Django 4.2.8 on 2026-03-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_challenge_userchallenge'),
        ('api', '0018_userbadge'),
    ]

    operations = [
    ]
