# Generated by Django 4.2.8 on 2026-03-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021 merge schedule fields and challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedule',
            name='adjustment_log',
        ),
        migrations.AddField(
            model_name='userschedule',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When True, AI-suggested schedule adjustments are paused. The user has explicitly locked this schedule for the current cycle.'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed')], default='in_progress', max_length=20),
        ),
    ]
