# Generated by Django 4.2.8 on 2026-03-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_userschedule_adjustment_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='If True, this program requires a subscription to use.'),
        ),
    ]
